modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/DAQEM/JobsPlusRemastered/issues"
license = "MIT"

[[mods]]
modId = "jobsplus"
version = "${version}"
displayName = "Jobs+"
authors = "DAQEM"
logoFile = "icon.png"
description = '''

'''
#logoFile = ""

[[dependencies.jobsplus]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jobsplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jobsplus]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.jobsplus]]
modId = "supermartijn642configlib"
mandatory = true
versionRange = "[${config_library_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jobsplus]]
modId = "arc"
mandatory = true
versionRange = "[${arc_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jobsplus]]
modId = "itemrestrictions"
mandatory = true
versionRange = "[${item_restrictions_version},)"
ordering = "NONE"
side = "BOTH"