modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/DAQEM/JobsPlusRemastered/issues"
license = "MIT"

[[mods]]
modId = "jobsplus"
version = "${version}"
displayName = "Jobs+"
authors = "DAQEM"
logoFile = "icon.png"
description = '''

'''
#logoFile = ""

[[dependencies.jobsplus]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jobsplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jobsplus]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.jobsplus]]
modId = "supermartijn642configlib"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "AFTER"
side = "BOTH"